apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
  namespace: trading
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      name: trading-deployment
      labels:
        app: trading
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: trading-serviceaccount
      containers:
        - name: trading
          image: playeconomy01acr.azurecr.io/play.trading:1.0.3
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: playeconomy-01
            - name: ServiceSettings__Authority
              value: https://playeconomy-01.westus.cloudapp.azure.com/identity-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5006
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5006
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5006
            initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading
  ports:
    - port: 80
      targetPort: 5006

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
  annotations:
    azure.workload.identity/client-id: 7ccca8bb-12e7-4a7e-914b-782543302139
  labels:
    azure.workload.identity/use: "true"
  